# global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  - job_name: 'api_menu'
    static_configs:
      - targets: ['api_menu:15000']

  - job_name: 'api_order'
    static_configs:
      - targets: ['api_order:15001']

  - job_name: 'api_store'
    static_configs:
      - targets: ['api_store:15002']