global:
  resolve_timeout: 5m

route:
  group_by: ['Selfmonitoring', 'Endpointmonitoring']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://127.0.0.1:5001/' #告警web.hook地址，告警資訊會post到該地址，需要編寫服務接收該告警資料

  - name: 'gmail'
    email_configs:
      - to: 'sinkwoyin@gmail.com'
        from: 'sinkwoyin@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'sinkwoyin@gmail.com'
        auth_identity: 'sinkwoyin@gmail.com'
        auth_password: 'wccmmbywalucgusa'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning' #目標告警狀態
    equal: ['alertname', 'dev', 'instance']